import React from 'react'

export default function banner() {
    return (
     <section className="main-banner cursor-light bg-1" id="main-banner">
  <h4 className="d-none">heading</h4>
  <div id="rev_slider_1_1_wrapper" className="rev_slider_wrapper fullscreen-container" data-alias="megaone-food-slider1" data-source="gallery" style={{background: 'transparent', padding: 0}}>
    {/* START REVOLUTION SLIDER 5.4.8.1 fullscreen mode */}
    <div id="rev_slider_1_1" className="rev_slider fullscreenbanner" style={{display: 'none'}} data-version="5.4.8.1">
      <ul>	{/* SLIDE  */}
        <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed={300} data-rotate={0} data-saveperformance="off" data-title="Slide" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
          {/* MAIN IMAGE */}
          {/*<img src="img/transparent.png" data-bgcolor='#ffffff' style='background:#ffffff' alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>*/}
          {/* LAYERS */}
          {/* LAYER NR. 1 */}
          <div className="tp-caption   tp-resizeme" id="slide-1-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-170','-186','-172','-100']" data-fontsize="['18','40','25','20']" data-lineheight="['70','70','40','40']" data-width="['none','none','280','200']" data-height="['none','150','150','150']" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:339.84375,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:[100%];s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:.7;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 5, whiteSpace: 'nowrap', fontSize: 28, lineHeight: 70, fontWeight: 300, opacity: '.8', color: '#ffffff', letterSpacing: 0, fontFamily: '"Roboto", sans-serif'}}>Best in Kolkata, West Bengal</div>
          {/* LAYER NR. 2 */}
          <div className="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-1-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-30','-84','-97','-20']" data-fontsize="['90','70','70','20']" data-lineheight="['85','85','60','50']" data-width="['470','670','670','400']" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:829.8828125,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 6, fontSize: 100, lineHeight: 80, fontWeight: 500, letterSpacing: 0, fontFamily: '"Grand Hotel", cursive'}}><span className="color-white">Wah! Phuchka </span> </div>
          {/* LAYER NR. 3 */}
          <div className="tp-caption   tp-resizeme" id="slide-1-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['133','25','60','160']" data-fontsize="['15','18','18','20']" data-lineheight="['30','26','26','26']" data-width="['580','570','580','400']" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1319.921875,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:.7;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 7, minWidth: 570, maxWidth: 570, whiteSpace: 'normal', fontSize: 18, lineHeight: 26, fontWeight: 300, color: '#ffffff', opacity: '.8', letterSpacing: 0, fontFamily: '"Roboto", sans-serif'}}> No more apprehensions about hygiene or quality. We got you all covered. Choose from our specialties! And enjoy the art of subtle flavours.</div>
          {/* LAYER NR. 5 */}
          {/*                    ele 1*/}
          <div className="tp-caption   tp-resizeme" id="slide-1-layer-6" data-x="['left','left','left','left']" data-hoffset="['-50','137','5000','5000']" data-y="['top','top','top','top']" data-voffset="['250','538','642','526']" data-width="none" data-height="none" data-whitespace="normal" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:719.921875,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 9}}>
            <div className="rs-looped rs-pendulum" data-easing data-startdeg={-5} data-enddeg={5} data-speed={3} data-origin="80% 60%"><img src="food-delivery/img/slider-ele1.png" alt data-ww="['267px','184px','145px','145px']" data-hh="['270px','186px','146px','146px']" data-no-retina /> </div></div>
          {/* LAYER NR. 6 */}
          {/*                    //ele 3*/}
          <div className="tp-caption   tp-resizeme" id="slide-1-layer-8" data-x="['right','right','right','right']" data-hoffset="['-230','-144','-100','-50']" data-y="['middle','top','bottom','bottom']" data-voffset="['40','100','112','80']" data-width="none" data-height="none" data-whitespace="normal" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:359.9609375,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 10}}><img data-depth="0.03" src="food-delivery/img/slider-ele3.png" alt data-ww="['545px','327px','264px','174px']" data-hh="['498px','299px','251px','161px']" data-no-retina /> </div>
          {/* LAYER NR. 10 */}
          {/*                    ele 5*/}
          <div className="tp-caption   tp-resizeme rs-parallaxlevel-0" id="slide-1-layer-13" data-x="['left','center','left','left']" data-hoffset="['1025','330','396','250']" data-y="['top','top','top','top']" data-voffset="['210','130','78','60']" data-width="none" data-height="none" data-whitespace="normal" data-visibility="['on','on','off','off']" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:50,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 14}}>
            <div className="rs-looped rs-pendulum" data-easing="easeInOutQuart" data-startdeg={-5} data-enddeg={5} data-speed={5} data-origin="80% 50%"><img src="food-delivery/img/slider-ele5.png" alt data-ww="['90px','105px','105px','105px']" data-hh="['85px','103px','103px','103px']" data-no-retina /> </div></div>
          {/* LAYER NR. 11 */}
          {/*                    ele 4*/}
          <div className="tp-caption   tp-resizeme" id="slide-1-layer-15" data-x="['left','left','left','left']" data-hoffset="['-1','-1','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['10','0','0','0']" data-width="none" data-height="none" data-whitespace="normal" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:9.9609375,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 15}}><img data-depth="0.05" src="food-delivery/img/slider-ele4.png" alt data-ww="['199px','191px','200px','150px']" data-hh="['270px','301px','259px','200px']" data-no-retina /> </div>
        </li>
      </ul>
      <div className="tp-bannertimer tp-bottom" style={{visibility: 'hidden !important'}} />	</div>
  </div>
  {/* END REVOLUTION SLIDER */}
  <div className="slider-icons">
    <ul className="slider-social banner-social">
      <li className="animated-wrap"><a className="animated-element" href="https://www.facebook.com/wahphuchka/" target="_blank"><i className="fab fa-facebook-f" /> </a></li>
      <li className="animated-wrap"><a className="animated-element" href="https://www.instagram.com/wahphuchka/" target="_blank"><i className="fab fa-instagram" /> </a></li>
      <li className="animated-wrap"><a className="animated-element" href="https://in.linkedin.com/company/wah-phuchka" target="_blank"><i className="fab fa-linkedin-in" /> </a></li>
    </ul>
  </div>
</section>

    )
}
